### ISSUE TITLE
I'd love to know why each config statement is needed...

### ISSUE THREAD

**Issue by dimaqq** [taxintt/fastapi-with-otel#3]
I'm looking at:
* https://github.com/taxintt/fastapi-with-otel/blob/7649aba51b7838a69ce39b04bdd22f4ababce974/app/src/main.py#L14-L16 and
* https://github.com/taxintt/fastapi-with-otel/blob/main/app/src/config/opentelemetry.py 

and I have so many questions... like what does each of these statements do?

my current level is that I tried to follow the official otel+fastapi doc and nothing is sent at all.

clearly your setup is more verbose and I presume that it works, which leaves me wondering what the key steps are and what they do.

P.S. I'm an OTEL noob, just trying to add it to my project so that other folks get the data from my service.

**Comment by taxintt** [comment]
Hi, @dimaqq.
I hope the below might help you to understand the overview of otel.
https://opentelemetry.io/docs/

In the setup in opentelemetry.py, I create an instance of trace-provider (`initialize_tracer_provider()`) and pass a specified exporter to the provider (`setup_span_exporter()`).
These are the components to send telemetry data to backends such as Datadog and Cloud Trace.

- https://opentelemetry.io/docs/concepts/signals/traces/#tracer-provider
- https://opentelemetry.io/docs/concepts/data-collection/

If you want to send telemetry data to the console, you can implement it like this.
```python
span_exporter=ConsoleSpanExporter()
```

If you use [Cloud Trace (GCP)](https://cloud.google.com/trace/docs/setup/python-ot?hl=ja), can implement it like this.
(The implementation depends on the backend, so I recommend to refer the docs of each service.)
```python
span_exporter=CloudTraceSpanExporter(
    project_id=os.environ.get("GCP_PROJECT"),
)
```

And `setup_fastapi_instrumentor(app)` is for [automatic instrumentation for Fast API based application](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-fastapi).
This is a package that implements the process of sending telemetry data available for each language and framework and can be used to perform instrumentation without writing code for Span generation like the below.

```python
tracer = trace.get_tracer_provider().get_tracer(__name__)
with tracer.start_as_current_span("get_sample"):
    time.sleep(2)
    return {"sample_id": random.randint(1, 10)}
```

see: https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py

> my current level is that I tried to follow the official otel+fastapi doc and nothing is sent at all.

If no data was sent, it may be a good idea to review the exporter settings and whether the provider is using the exporter properly.

Thanks!
